In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.shape

(4,)

In [9]:
a.dtype

dtype('int32')

In [10]:
b=np.array([[1,2,3],[4,5,6],[2,4,6]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6]])

In [11]:
b.shape

(3, 3)

In [12]:
b[2][2]

6

In [13]:
b[3][3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [14]:
b[1][1]=3

In [15]:
b

array([[1, 2, 3],
       [4, 3, 6],
       [2, 4, 6]])

In [19]:
l1=(i for i in range(20))
list(l1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [21]:
np.array=np.arange(20)
np.array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
np.a=np.arange(10)
np.a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.b=np.a+1
np.b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
%timeit np.arange(1000)**3

5.02 µs ± 218 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [29]:
%timeit [i**3 for i in range(1000)]

250 µs ± 14.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(5,50)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [32]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [36]:
np.arange(50,5,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6])

In [37]:
np.arange(49,4,-2)

array([49, 47, 45, 43, 41, 39, 37, 35, 33, 31, 29, 27, 25, 23, 21, 19, 17,
       15, 13, 11,  9,  7,  5])

In [39]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.zeros([3,3], dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [44]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [45]:
np.ones([2,2],dtype=np.int32)

array([[1, 1],
       [1, 1]])

In [52]:
a=np.array([[1,2],[3,4],[4,6]])
a

TypeError: 'numpy.ndarray' object is not callable

In [53]:
a = np.array([[2, 3], [2, 4], [8, 9]])
print(a)

TypeError: 'numpy.ndarray' object is not callable

In [57]:
np.full([5,3],3.3)

array([[3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3]])

In [60]:
np.full([2,4],3.3,dtype=np.int32)

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [66]:
np.eye(4,dtype=np.int32)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [68]:
np.diag([2,4,5,8])

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 8]])

In [7]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [8]:
a[1]

2