In [1]:
import numpy as np

In [2]:
a=np.array([[1,2],[3,4],[5,5]])
a

array([[1, 2],
       [3, 4],
       [5, 5]])

In [9]:
a[1][1]

4

In [11]:
a[[1,2]]

array([[3, 4],
       [5, 5]])

In [12]:
a[1]

array([3, 4])

In [15]:
b=np.array([1,2,3,4,5,6,7,8,9,10])
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
b[2]

3

In [19]:
b[[0,4]]

array([1, 5])

In [26]:
b[[-6,4]]

array([5, 5])

In [27]:
a

array([[1, 2],
       [3, 4],
       [5, 5]])

In [28]:
b[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
b[::3]

array([ 1,  4,  7, 10])

In [30]:
a

array([[1, 2],
       [3, 4],
       [5, 5]])

In [32]:
a[0:1]

array([[1, 2]])

In [33]:
a[1:1]

array([], shape=(0, 2), dtype=int32)

In [34]:
a[0:1,0:1]

array([[1]])

In [35]:
a = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11],[12, 13, 14, 15]])


In [36]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
a[0:4,0:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [79]:
a[1:4,1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [81]:
a<5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [83]:
a[a<5]

array([0, 1, 2, 3, 4])

In [84]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
b=a

In [86]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
b[1][1]=4

In [89]:
a

array([[ 0,  1,  2,  3],
       [ 4,  4,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
np.shares_memory(a,b)

True

In [92]:
a

array([[ 0,  1,  2,  3],
       [ 4,  4,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
b

array([[ 0,  1,  2,  3],
       [ 4,  4,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
b=a.copy()

In [95]:
b

array([[ 0,  1,  2,  3],
       [ 4,  4,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [96]:
b[1][1]=5

In [97]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [98]:
a

array([[ 0,  1,  2,  3],
       [ 4,  4,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [1]:
import numpy as np

In [2]:
print(np.random.random())

0.9149259940274033


In [19]:
np.random.seed(10)
print(np.random.random())
print(np.random.random())

0.771320643266746
0.0207519493594015


In [24]:
x=np.random.random((4,4))
x

array([[0.63364823, 0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226],
       [0.81262096, 0.61252607, 0.72175532, 0.29187607]])

In [26]:
num=np.random.randint(low=10,high=20)
num

16

In [29]:
num=np.random.randint(low=10,high=20,size=(5,5))
num

array([[17, 11, 14, 10, 18],
       [15, 14, 17, 18, 18],
       [12, 16, 12, 18, 18],
       [16, 16, 15, 16, 10],
       [10, 16, 19, 11, 18]])

In [30]:
a = [24,27,22,47,35,82,-33,25,2.3,18]
a

[24, 27, 22, 47, 35, 82, -33, 25, 2.3, 18]

In [31]:
np.random.choice(a,size=(3,3))

array([[18. , 27. , 22. ],
       [ 2.3, 18. , 18. ],
       [82. , 24. , 22. ]])

In [34]:
nd=np.random.random((4,4))
nd

array([[1.34563003e-01, 6.04726160e-01, 2.83148276e-01, 5.06407820e-01],
       [3.84604283e-02, 3.32444096e-01, 2.72531491e-04, 6.64655466e-01],
       [3.77440665e-01, 7.47581968e-01, 1.40575782e-01, 3.88049453e-01],
       [8.66491641e-01, 9.56853326e-01, 4.86553669e-01, 1.05933059e-01]])

In [37]:
nr=np.round(nd,3)
nr

array([[0.135, 0.605, 0.283, 0.506],
       [0.038, 0.332, 0.   , 0.665],
       [0.377, 0.748, 0.141, 0.388],
       [0.866, 0.957, 0.487, 0.106]])

In [40]:
s=nr*100
s

array([[13.5, 60.5, 28.3, 50.6],
       [ 3.8, 33.2,  0. , 66.5],
       [37.7, 74.8, 14.1, 38.8],
       [86.6, 95.7, 48.7, 10.6]])

In [42]:
new=s.astype(int)
new

array([[13, 60, 28, 50],
       [ 3, 33,  0, 66],
       [37, 74, 14, 38],
       [86, 95, 48, 10]])

In [44]:
new=s.astype(float)
new

array([[13.5, 60.5, 28.3, 50.6],
       [ 3.8, 33.2,  0. , 66.5],
       [37.7, 74.8, 14.1, 38.8],
       [86.6, 95.7, 48.7, 10.6]])

In [46]:
x=np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
x.shape

(20,)

In [51]:
x.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
x.reshape(2,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [54]:
x=x.reshape(-1)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [57]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [58]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [59]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462])

In [66]:
np.random.seed(10)
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [67]:
a.shape

(20,)

In [70]:
n=np.arange(1,10).reshape(3,3)
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
np.sum(n)

45

In [79]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
np.sum(n,axis=0)

array([12, 15, 18])

In [81]:
np.sum(n,axis=1)

array([ 6, 15, 24])

In [84]:
b=n.T
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [86]:
a = np.array([1,4,2,6,10,13,5,7,3])
a

array([ 1,  4,  2,  6, 10, 13,  5,  7,  3])

In [88]:
a.max()

13

In [89]:
a.min()

1

In [90]:
a.argmax()

5

In [91]:
a.argmin()

0

In [92]:
np.sort(a)

array([ 1,  2,  3,  4,  5,  6,  7, 10, 13])

In [93]:
np.argsort(a)

array([0, 2, 8, 1, 6, 3, 7, 4, 5], dtype=int64)