In [1]:
import numpy as np
import pandas as pd

In [2]:
s=np.array([1,2,3,4])
s

array([1, 2, 3, 4])

In [7]:
f=pd.Series(s)
print(f)

0    1
1    2
2    3
3    4
dtype: int32


In [8]:
type(f)

pandas.core.series.Series

In [9]:
type(s)

numpy.ndarray

In [100]:
arr=np.array(['a','b','c','d'])
arr
s=pd.Series(arr, index=[100,101,102,103])
s

100    a
101    b
102    c
103    d
dtype: object

In [24]:
a=pd.Series(arr,index=[10,20,30,40])
a

10    a
20    b
30    c
40    d
dtype: object

In [28]:
#dictionaries
dict1 = {'a': 1 , 'b': 2 , 'c': 3}
dict1

{'a': 1, 'b': 2, 'c': 3}

In [29]:
type(dict1)

dict

In [34]:
s=pd.Series(dict1)
s

a    1
b    2
c    3
dtype: int64

In [33]:
type(s)

pandas.core.series.Series

In [22]:
s=pd.Series('a',index=[1,2,3,4])
s

1    a
2    a
3    a
4    a
dtype: object

In [36]:
s=pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [37]:
s[2]

3

In [38]:
s[::3]

0    1
3    4
dtype: int64

In [39]:
s[:-1]

0    1
1    2
2    3
dtype: int64

In [43]:
s[-4: ]

0    1
1    2
2    3
3    4
dtype: int64

In [45]:
s=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])
s

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [47]:
s['a']

1

In [50]:
s['a':'d']

a    1
b    2
c    3
d    4
dtype: int64

In [51]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [52]:
s.values

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [61]:
#dataframes
name=['akshay','shraddha','kartheek']
age=['21','23','25']
indexes=['first person','second person','third person']
dict1={'Name':name,'Age':age}
s=pd.DataFrame(dict1,index=indexes)
print(s)

                   Name Age
first person     akshay  21
second person  shraddha  23
third person   kartheek  25


In [64]:
name=['akshay','abhi','kiran','abhilash']
age=['21','22','23','21']
hobies=['cricket','pubg','oyo','driving']
indexes=['boy1','boy2','boy3','boy4']
dict1={'Name':name,'Age':age,'hobies':hobies}
btech=pd.DataFrame(dict1,index=indexes)
print(btech)

          Name Age   hobies
boy1    akshay  21  cricket
boy2      abhi  22     pubg
boy3     kiran  23      oyo
boy4  abhilash  21  driving


In [65]:
s['Name']

first person       akshay
second person    shraddha
third person     kartheek
Name: Name, dtype: object

In [66]:
btech['Name']

boy1      akshay
boy2        abhi
boy3       kiran
boy4    abhilash
Name: Name, dtype: object

In [73]:
btech['boy1':'boy4':2]

Name Age   hobies
boy1  akshay  21  cricket
boy3   kiran  23      oyo

In [75]:
s['hobies']=['cricket','cooking','shopping']
s

Name Age    hobies
first person     akshay  21   cricket
second person  shraddha  23   cooking
third person   kartheek  25  shopping

In [80]:
random=np.random.randint(low=0,high=30,size=30)
name=np.random.choice(['a','b','c','d'],size=30)
choice=np.random.choice([10,20,30,40,50],size=30)
dict1={'Random':random,'Name':name,'choice':choice}
p=pd.DataFrame(dict1)
print(p)

    Random Name  choice
0       16    c      50
1       14    d      20
2       27    b      40
3        4    c      20
4        4    b      40
5       11    b      50
6       10    a      50
7       10    d      40
8       21    a      40
9       27    c      30
10       9    c      40
11      21    a      40
12      27    b      30
13      17    a      10
14       6    c      40
15      18    a      30
16      17    b      10
17      11    b      40
18       7    a      30
19      10    b      20
20      18    c      40
21      21    a      20
22      16    a      30
23      22    c      20
24      25    c      30
25       4    b      30
26      21    c      20
27      12    a      20
28       1    c      30
29       3    a      10


In [81]:
p.shape

(30, 3)

In [82]:
type(p)

pandas.core.frame.DataFrame

In [83]:
p.values

array([[16, 'c', 50],
       [14, 'd', 20],
       [27, 'b', 40],
       [4, 'c', 20],
       [4, 'b', 40],
       [11, 'b', 50],
       [10, 'a', 50],
       [10, 'd', 40],
       [21, 'a', 40],
       [27, 'c', 30],
       [9, 'c', 40],
       [21, 'a', 40],
       [27, 'b', 30],
       [17, 'a', 10],
       [6, 'c', 40],
       [18, 'a', 30],
       [17, 'b', 10],
       [11, 'b', 40],
       [7, 'a', 30],
       [10, 'b', 20],
       [18, 'c', 40],
       [21, 'a', 20],
       [16, 'a', 30],
       [22, 'c', 20],
       [25, 'c', 30],
       [4, 'b', 30],
       [21, 'c', 20],
       [12, 'a', 20],
       [1, 'c', 30],
       [3, 'a', 10]], dtype=object)

In [84]:
p.columns

Index(['Random', 'Name', 'choice'], dtype='object')

In [85]:
p.head()

Random Name  choice
0      16    c      50
1      14    d      20
2      27    b      40
3       4    c      20
4       4    b      40

In [86]:
p.tail()

Random Name  choice
25       4    b      30
26      21    c      20
27      12    a      20
28       1    c      30
29       3    a      10

In [87]:
p.head(15)

Random Name  choice
0       16    c      50
1       14    d      20
2       27    b      40
3        4    c      20
4        4    b      40
5       11    b      50
6       10    a      50
7       10    d      40
8       21    a      40
9       27    c      30
10       9    c      40
11      21    a      40
12      27    b      30
13      17    a      10
14       6    c      40

In [88]:
p.tail(15)

Random Name  choice
15      18    a      30
16      17    b      10
17      11    b      40
18       7    a      30
19      10    b      20
20      18    c      40
21      21    a      20
22      16    a      30
23      22    c      20
24      25    c      30
25       4    b      30
26      21    c      20
27      12    a      20
28       1    c      30
29       3    a      10

In [89]:
p.info

<bound method DataFrame.info of     Random Name  choice
0       16    c      50
1       14    d      20
2       27    b      40
3        4    c      20
4        4    b      40
5       11    b      50
6       10    a      50
7       10    d      40
8       21    a      40
9       27    c      30
10       9    c      40
11      21    a      40
12      27    b      30
13      17    a      10
14       6    c      40
15      18    a      30
16      17    b      10
17      11    b      40
18       7    a      30
19      10    b      20
20      18    c      40
21      21    a      20
22      16    a      30
23      22    c      20
24      25    c      30
25       4    b      30
26      21    c      20
27      12    a      20
28       1    c      30
29       3    a      10>

In [90]:
p.describe

<bound method NDFrame.describe of     Random Name  choice
0       16    c      50
1       14    d      20
2       27    b      40
3        4    c      20
4        4    b      40
5       11    b      50
6       10    a      50
7       10    d      40
8       21    a      40
9       27    c      30
10       9    c      40
11      21    a      40
12      27    b      30
13      17    a      10
14       6    c      40
15      18    a      30
16      17    b      10
17      11    b      40
18       7    a      30
19      10    b      20
20      18    c      40
21      21    a      20
22      16    a      30
23      22    c      20
24      25    c      30
25       4    b      30
26      21    c      20
27      12    a      20
28       1    c      30
29       3    a      10>

In [92]:
p['Name'].describe

<bound method NDFrame.describe of 0     c
1     d
2     b
3     c
4     b
5     b
6     a
7     d
8     a
9     c
10    c
11    a
12    b
13    a
14    c
15    a
16    b
17    b
18    a
19    b
20    c
21    a
22    a
23    c
24    c
25    b
26    c
27    a
28    c
29    a
Name: Name, dtype: object>

In [1]:
#csv file handlinghttp://localhost:8889/edit/Downloads/SampleCSVFile_2kb%20(1).csv
sample_df=pd.read_csv('Downloads\Sample100.csv')

NameError: name 'pd' is not defined

In [104]:
sample_df

Serial Number                   Company Name  Employee Markme  \
0   9788189999599                 TALES OF SHIVA             Mark   
1   9780099578079      1Q84 THE COMPLETE TRILOGY  HARUKI MURAKAMI   
2   9780198082897                       MY KUMAN             Mark   
3   9780007880331        THE GOD OF SMAAL THINGS    ARUNDHATI ROY   
4   9780545060455               THE BLACK CIRCLE             Mark   
..            ...                            ...              ...   
94  9788184821536  MORE STORIES FROM THE JATAKAS             Mark   
95  9788184821543           MORE TALES OF BIRBAL                -   
96  9788184821550         TALES FROM THE JATAKAS                -   
97  9788184821567               RAMarkS OF MEWAR                -   
98  9788184821574       THE SONS OF THE PANDAVAS                -   

           Description  Leave  
0                 mark      0  
1                 Mark      0  
2                 Mark      0  
3   4TH HARPER COLLINS      2  
4   4TH HARPER COLLINS      0  
..                 ...    ...  
94                 ACK      0  
95                 ACK      0  
96                 ACK      0  
97                 ACK      0  
98                 ACK      0  

[99 rows x 5 columns]

In [105]:
type(sample_df)

pandas.core.frame.DataFrame

In [109]:
(sample_df).head()

Serial Number               Company Name  Employee Markme  \
0  9788189999599             TALES OF SHIVA             Mark   
1  9780099578079  1Q84 THE COMPLETE TRILOGY  HARUKI MURAKAMI   
2  9780198082897                   MY KUMAN             Mark   
3  9780007880331    THE GOD OF SMAAL THINGS    ARUNDHATI ROY   
4  9780545060455           THE BLACK CIRCLE             Mark   

          Description  Leave  
0                mark      0  
1                Mark      0  
2                Mark      0  
3  4TH HARPER COLLINS      2  
4  4TH HARPER COLLINS      0

In [110]:
sample_df.tail()

Serial Number                   Company Name Employee Markme Description  \
94  9788184821536  MORE STORIES FROM THE JATAKAS            Mark         ACK   
95  9788184821543           MORE TALES OF BIRBAL               -         ACK   
96  9788184821550         TALES FROM THE JATAKAS               -         ACK   
97  9788184821567               RAMarkS OF MEWAR               -         ACK   
98  9788184821574       THE SONS OF THE PANDAVAS               -         ACK   

    Leave  
94      0  
95      0  
96      0  
97      0  
98      0

In [111]:
sample_df.shape

(99, 5)

In [113]:
sample_df.values

array([[9788189999599, 'TALES OF SHIVA', 'Mark', 'mark', 0],
       [9780099578079, '1Q84 THE COMPLETE TRILOGY', 'HARUKI MURAKAMI',
        'Mark', 0],
       [9780198082897, 'MY KUMAN', 'Mark', 'Mark', 0],
       [9780007880331, 'THE GOD OF SMAAL THINGS', 'ARUNDHATI ROY',
        '4TH HARPER COLLINS', 2],
       [9780545060455, 'THE BLACK CIRCLE', 'Mark', '4TH HARPER COLLINS',
        0],
       [9788126525072, 'THE THREE LAWS OF PERFORMANCE', 'Mark',
        '4TH HARPER COLLINS', 0],
       [9789381626610, 'CHAMarkKYA MANTRA', 'Mark', '4TH HARPER COLLINS',
        0],
       [9788184513523, '59.FLAGS', 'Mark', '4TH HARPER COLLINS', 0],
       [9780743234801, 'THE POWER OF POSITIVE THINKING FROM', 'Mark',
        'A & A PUBLISHER', 0],
       [9789381529621, 'YOU CAN IF YO THINK YO CAN', 'PEALE',
        'A & A PUBLISHER', 0],
       [9788183223966, 'DONGRI SE DUBAI TAK (MPH)', 'Mark',
        'A & A PUBLISHER', 0],
       [9788187776005, 'MarkLANDA ADYTAN KOSH', 'Mark',
        'AADI

In [114]:
sample_df.columns

Index(['Serial Number', 'Company Name', 'Employee Markme', 'Description',
       'Leave'],
      dtype='object')

In [118]:
sample_df.set_index('Serial Number',inplace=False)
sample_df

KeyError: "None of ['Serial Number'] are in the columns"

In [119]:
sample_df.sort_index(ascending=True)

Company Name   Employee Markme  \
Serial Number                                                                  
8187776021            MarkLANDA CONCISE DICT(ENG TO HINDI)              Mark   
9780007880331                      THE GOD OF SMAAL THINGS     ARUNDHATI ROY   
9780099578079                    1Q84 THE COMPLETE TRILOGY   HARUKI MURAKAMI   
9780198082897                                     MY KUMAN              Mark   
9780349121420                          THE ART OF CHOOSING  SHEEMark IYENGAR   
...                                                    ...               ...   
9789384850357               DON'T TEACH ME TOLERANCE INDIA      DEEP TRIVEDI   
9789384850364           MUJHE SAHISHNUTA MAT SIKHAO BHARAT      DEEP TRIVEDI   
9789384850746                           SECRETS OF DESTINY      DEEP TRIVEDI   
9789384850753  BHAGYA KE RAHASYA (HINDI) SECRET OF DESTINY      DEEP TRIVEDI   
9789386361011               INDIAN HERITAGE ,ART & CULTURE          MADHUKAR   

                                   Description  Leave  
Serial Number                                          
8187776021                   AADISH BOOK DEPOT      0  
9780007880331               4TH HARPER COLLINS      2  
9780099578079                             Mark      0  
9780198082897                             Mark      0  
9780349121420                           ABACUS      0  
...                                        ...    ...  
9789384850357       AATMAN INNOVATIONS PVT LTD      0  
9789384850364       AATMAN INNOVATIONS PVT LTD      0  
9789384850746       AATMAN INNOVATIONS PVT LTD      1  
9789384850753       AATMAN INNOVATIONS PVT LTD      1  
9789386361011  ACCESS PUBLISHING INDIA PVT.LTD     10  

[99 rows x 4 columns]

In [120]:
sample_df.sort_index(ascending=False)

Company Name   Employee Markme  \
Serial Number                                                                  
9789386361011               INDIAN HERITAGE ,ART & CULTURE          MADHUKAR   
9789384850753  BHAGYA KE RAHASYA (HINDI) SECRET OF DESTINY      DEEP TRIVEDI   
9789384850746                           SECRETS OF DESTINY      DEEP TRIVEDI   
9789384850364           MUJHE SAHISHNUTA MAT SIKHAO BHARAT      DEEP TRIVEDI   
9789384850357               DON'T TEACH ME TOLERANCE INDIA      DEEP TRIVEDI   
...                                                    ...               ...   
9780349121420                          THE ART OF CHOOSING  SHEEMark IYENGAR   
9780198082897                                     MY KUMAN              Mark   
9780099578079                    1Q84 THE COMPLETE TRILOGY   HARUKI MURAKAMI   
9780007880331                      THE GOD OF SMAAL THINGS     ARUNDHATI ROY   
8187776021            MarkLANDA CONCISE DICT(ENG TO HINDI)              Mark   

                                   Description  Leave  
Serial Number                                          
9789386361011  ACCESS PUBLISHING INDIA PVT.LTD     10  
9789384850753       AATMAN INNOVATIONS PVT LTD      1  
9789384850746       AATMAN INNOVATIONS PVT LTD      1  
9789384850364       AATMAN INNOVATIONS PVT LTD      0  
9789384850357       AATMAN INNOVATIONS PVT LTD      0  
...                                        ...    ...  
9780349121420                           ABACUS      0  
9780198082897                             Mark      0  
9780099578079                             Mark      0  
9780007880331               4TH HARPER COLLINS      2  
8187776021                   AADISH BOOK DEPOT      0  

[99 rows x 4 columns]